### ISSUE TITLE
Wifi information is not retrieved in iOS 13 an higher versions

### ISSUE THREAD

**Issue by bgavas** [Feghal/FGRoute#2]
It works properly below iOS version 13, but it does not work in iOS 13 and higher. The issue may be about some permissions.

**Comment by Feghal** [comment]
@bgavas I updated readme file and example app, you need to add "Access WiFi Information" entitlement and have location access, VPN app or use NEHotspotConfiguration. I have tested on ios 13 with the location access and it is working, so I am closing the issue.
